## The following two function compute the inverse of a given matrix and cache it.
## makeCacheMatrix() creates an R object which contains a matrix and several
## functions to store and retrieve the matrix and its inverse. 
## The actual calculation of the inverse matrix is done by cacheSolve. However it
## only calculates the inverse if it hasn't been cached before.
## The inverse of the matrix can only be computed if the matrix is invertible.
## Otherwise an error is thrown.

## This function serves as an R object with a list of functions to store (cache) 
## and retrieve a matrix object as well as its reverse. Its argument is a simple matrix.

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    
    setMatrix <- function(m) {
        x <<- m
        inv <<- NULL
    }
    
    getMatrix <- function() x
    
    setInverseMatrix <- function(inv_m) inv <<- inv_m
    
    getInverseMatrix <- function() inv
    
    list(setMatrix = setMatrix, 
         getMatrix = getMatrix,
         setInverseMatrix = setInverseMatrix,
         getInverseMatrix = getInverseMatrix)
}


## This function delivers the inverse of a given matrix. If the inverse has been 
## calculated and cached before then the cached inversed will be delivered.
## Otherwise the inverse will be calculated, stored in the cache and then 
## delivered.
## The argument must be of the "special" matrix type generated by the function
## makeCacheMatrix.
## The function only works with an invertible matrix. If the matrix is not 
## invertible, en error is thrown.

cacheSolve <- function(x, ...) {
    inv <- x$getInverseMatrix()
    if (! is.null(inv)) {
        message("getting cached inverse of matrix")
        return(inv)
    }
    matr <- x$getMatrix()
    inv <- solve(matr, ...)
    x$setInverseMatrix(inv)
    inv
}
